const pitchers = [
    {
    "result": "home_run",
    "gen_velocity": "10.52",
    "pitcher_team_id": "119",
    "pitcher_team_abbrev": "LAD",
    "pitcher": "Kershaw, Clayton",
    "batter_team": "Mets",
    "distance": "414.59",
    "top_inning": "Y",
    "height": "87.02",
    "batter_id": "502517",
    "game_id": "2015/10/09/nynmlb-lanmlb-1",
    "launch_speed": "104.92",
    "pitcher_id": "477132",
    "pitcher_last_init": "Kershaw, C",
    "batter_last_init": "Murphy, D",
    "game_date": "2015-10-09T00:00:00",
    "pitcher_team": "Dodgers",
    "inning": "4",
    "game_pk": "446244",
    "batter": "Murphy, Daniel",
    "batter_team_id": "121",
    "pitch_speed": "94.41",
    "launch_angle": "26.85",
    "trajectory": "line_drive",
    "batter_team_abbrev": "NYM"
    },
    {
    "result": "home_run",
    "gen_velocity": "14.13",
    "pitcher_team_id": "121",
    "pitcher_team_abbrev": "NYM",
    "pitcher": "deGrom, Jacob",
    "batter_team": "Cubs",
    "distance": "424.45",
    "top_inning": "N",
    "height": "62.74",
    "batter_id": "624585",
    "game_id": "2015/10/20/nynmlb-chnmlb-1",
    "launch_speed": "110.19",
    "pitcher_id": "594798",
    "pitcher_last_init": "deGrom, J",
    "batter_last_init": "Soler, J",
    "game_date": "2015-10-20T00:00:00",
    "pitcher_team": "Mets",
    "inning": "4",
    "game_pk": "446265",
    "batter": "Soler, Jorge",
    "batter_team_id": "112",
    "pitch_speed": "96.06",
    "launch_angle": "20.56",
    "trajectory": "fly_ball",
    "batter_team_abbrev": "CHC"
    },
    {
    "result": "home_run",
    "gen_velocity": "20.99",
    "pitcher_team_id": "141",
    "pitcher_team_abbrev": "TOR",
    "pitcher": "Price, David",
    "batter_team": "Royals",
    "distance": "405.74",
    "top_inning": "N",
    "height": "51.58",
    "batter_id": "519058",
    "game_id": "2015/10/23/tormlb-kcamlb-1",
    "launch_speed": "109.20",
    "pitcher_id": "456034",
    "pitcher_last_init": "Price, D",
    "batter_last_init": "Moustakas, M",
    "game_date": "2015-10-23T00:00:00",
    "pitcher_team": "Blue Jays",
    "inning": "2",
    "game_pk": "446269",
    "batter": "Moustakas, Mike",
    "batter_team_id": "118",
    "pitch_speed": "88.21",
    "launch_angle": "17.87",
    "trajectory": "line_drive",
    "batter_team_abbrev": "KC"
    },
]

export default pitchers;